/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign4;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WordStatisticsData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WordStatisticsData\",\"namespace\":\"com.refactorlabs.cs378.assign4\",\"fields\":[{\"name\":\"wordCount\",\"type\":\"long\"},{\"name\":\"docCount\",\"type\":\"long\"},{\"name\":\"min\",\"type\":\"long\"},{\"name\":\"max\",\"type\":\"long\"},{\"name\":\"sumSquared\",\"type\":\"long\"},{\"name\":\"mean\",\"type\":\"double\"},{\"name\":\"variance\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long wordCount;
  @Deprecated public long docCount;
  @Deprecated public long min;
  @Deprecated public long max;
  @Deprecated public long sumSquared;
  @Deprecated public double mean;
  @Deprecated public double variance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public WordStatisticsData() {}

  /**
   * All-args constructor.
   */
  public WordStatisticsData(java.lang.Long wordCount, java.lang.Long docCount, java.lang.Long min, java.lang.Long max, java.lang.Long sumSquared, java.lang.Double mean, java.lang.Double variance) {
    this.wordCount = wordCount;
    this.docCount = docCount;
    this.min = min;
    this.max = max;
    this.sumSquared = sumSquared;
    this.mean = mean;
    this.variance = variance;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return wordCount;
    case 1: return docCount;
    case 2: return min;
    case 3: return max;
    case 4: return sumSquared;
    case 5: return mean;
    case 6: return variance;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: wordCount = (java.lang.Long)value$; break;
    case 1: docCount = (java.lang.Long)value$; break;
    case 2: min = (java.lang.Long)value$; break;
    case 3: max = (java.lang.Long)value$; break;
    case 4: sumSquared = (java.lang.Long)value$; break;
    case 5: mean = (java.lang.Double)value$; break;
    case 6: variance = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'wordCount' field.
   */
  public java.lang.Long getWordCount() {
    return wordCount;
  }

  /**
   * Sets the value of the 'wordCount' field.
   * @param value the value to set.
   */
  public void setWordCount(java.lang.Long value) {
    this.wordCount = value;
  }

  /**
   * Gets the value of the 'docCount' field.
   */
  public java.lang.Long getDocCount() {
    return docCount;
  }

  /**
   * Sets the value of the 'docCount' field.
   * @param value the value to set.
   */
  public void setDocCount(java.lang.Long value) {
    this.docCount = value;
  }

  /**
   * Gets the value of the 'min' field.
   */
  public java.lang.Long getMin() {
    return min;
  }

  /**
   * Sets the value of the 'min' field.
   * @param value the value to set.
   */
  public void setMin(java.lang.Long value) {
    this.min = value;
  }

  /**
   * Gets the value of the 'max' field.
   */
  public java.lang.Long getMax() {
    return max;
  }

  /**
   * Sets the value of the 'max' field.
   * @param value the value to set.
   */
  public void setMax(java.lang.Long value) {
    this.max = value;
  }

  /**
   * Gets the value of the 'sumSquared' field.
   */
  public java.lang.Long getSumSquared() {
    return sumSquared;
  }

  /**
   * Sets the value of the 'sumSquared' field.
   * @param value the value to set.
   */
  public void setSumSquared(java.lang.Long value) {
    this.sumSquared = value;
  }

  /**
   * Gets the value of the 'mean' field.
   */
  public java.lang.Double getMean() {
    return mean;
  }

  /**
   * Sets the value of the 'mean' field.
   * @param value the value to set.
   */
  public void setMean(java.lang.Double value) {
    this.mean = value;
  }

  /**
   * Gets the value of the 'variance' field.
   */
  public java.lang.Double getVariance() {
    return variance;
  }

  /**
   * Sets the value of the 'variance' field.
   * @param value the value to set.
   */
  public void setVariance(java.lang.Double value) {
    this.variance = value;
  }

  /** Creates a new WordStatisticsData RecordBuilder */
  public static com.refactorlabs.cs378.assign4.WordStatisticsData.Builder newBuilder() {
    return new com.refactorlabs.cs378.assign4.WordStatisticsData.Builder();
  }
  
  /** Creates a new WordStatisticsData RecordBuilder by copying an existing Builder */
  public static com.refactorlabs.cs378.assign4.WordStatisticsData.Builder newBuilder(com.refactorlabs.cs378.assign4.WordStatisticsData.Builder other) {
    return new com.refactorlabs.cs378.assign4.WordStatisticsData.Builder(other);
  }
  
  /** Creates a new WordStatisticsData RecordBuilder by copying an existing WordStatisticsData instance */
  public static com.refactorlabs.cs378.assign4.WordStatisticsData.Builder newBuilder(com.refactorlabs.cs378.assign4.WordStatisticsData other) {
    return new com.refactorlabs.cs378.assign4.WordStatisticsData.Builder(other);
  }
  
  /**
   * RecordBuilder for WordStatisticsData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WordStatisticsData>
    implements org.apache.avro.data.RecordBuilder<WordStatisticsData> {

    private long wordCount;
    private long docCount;
    private long min;
    private long max;
    private long sumSquared;
    private double mean;
    private double variance;

    /** Creates a new Builder */
    private Builder() {
      super(com.refactorlabs.cs378.assign4.WordStatisticsData.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.refactorlabs.cs378.assign4.WordStatisticsData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.wordCount)) {
        this.wordCount = data().deepCopy(fields()[0].schema(), other.wordCount);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.docCount)) {
        this.docCount = data().deepCopy(fields()[1].schema(), other.docCount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.min)) {
        this.min = data().deepCopy(fields()[2].schema(), other.min);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.max)) {
        this.max = data().deepCopy(fields()[3].schema(), other.max);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sumSquared)) {
        this.sumSquared = data().deepCopy(fields()[4].schema(), other.sumSquared);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.mean)) {
        this.mean = data().deepCopy(fields()[5].schema(), other.mean);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.variance)) {
        this.variance = data().deepCopy(fields()[6].schema(), other.variance);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing WordStatisticsData instance */
    private Builder(com.refactorlabs.cs378.assign4.WordStatisticsData other) {
            super(com.refactorlabs.cs378.assign4.WordStatisticsData.SCHEMA$);
      if (isValidValue(fields()[0], other.wordCount)) {
        this.wordCount = data().deepCopy(fields()[0].schema(), other.wordCount);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.docCount)) {
        this.docCount = data().deepCopy(fields()[1].schema(), other.docCount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.min)) {
        this.min = data().deepCopy(fields()[2].schema(), other.min);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.max)) {
        this.max = data().deepCopy(fields()[3].schema(), other.max);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sumSquared)) {
        this.sumSquared = data().deepCopy(fields()[4].schema(), other.sumSquared);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.mean)) {
        this.mean = data().deepCopy(fields()[5].schema(), other.mean);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.variance)) {
        this.variance = data().deepCopy(fields()[6].schema(), other.variance);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'wordCount' field */
    public java.lang.Long getWordCount() {
      return wordCount;
    }
    
    /** Sets the value of the 'wordCount' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setWordCount(long value) {
      validate(fields()[0], value);
      this.wordCount = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'wordCount' field has been set */
    public boolean hasWordCount() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'wordCount' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearWordCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'docCount' field */
    public java.lang.Long getDocCount() {
      return docCount;
    }
    
    /** Sets the value of the 'docCount' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setDocCount(long value) {
      validate(fields()[1], value);
      this.docCount = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'docCount' field has been set */
    public boolean hasDocCount() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'docCount' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearDocCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'min' field */
    public java.lang.Long getMin() {
      return min;
    }
    
    /** Sets the value of the 'min' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setMin(long value) {
      validate(fields()[2], value);
      this.min = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'min' field has been set */
    public boolean hasMin() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'min' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearMin() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'max' field */
    public java.lang.Long getMax() {
      return max;
    }
    
    /** Sets the value of the 'max' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setMax(long value) {
      validate(fields()[3], value);
      this.max = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'max' field has been set */
    public boolean hasMax() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'max' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearMax() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'sumSquared' field */
    public java.lang.Long getSumSquared() {
      return sumSquared;
    }
    
    /** Sets the value of the 'sumSquared' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setSumSquared(long value) {
      validate(fields()[4], value);
      this.sumSquared = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'sumSquared' field has been set */
    public boolean hasSumSquared() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'sumSquared' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearSumSquared() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'mean' field */
    public java.lang.Double getMean() {
      return mean;
    }
    
    /** Sets the value of the 'mean' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setMean(double value) {
      validate(fields()[5], value);
      this.mean = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'mean' field has been set */
    public boolean hasMean() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'mean' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearMean() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'variance' field */
    public java.lang.Double getVariance() {
      return variance;
    }
    
    /** Sets the value of the 'variance' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder setVariance(double value) {
      validate(fields()[6], value);
      this.variance = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'variance' field has been set */
    public boolean hasVariance() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'variance' field */
    public com.refactorlabs.cs378.assign4.WordStatisticsData.Builder clearVariance() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public WordStatisticsData build() {
      try {
        WordStatisticsData record = new WordStatisticsData();
        record.wordCount = fieldSetFlags()[0] ? this.wordCount : (java.lang.Long) defaultValue(fields()[0]);
        record.docCount = fieldSetFlags()[1] ? this.docCount : (java.lang.Long) defaultValue(fields()[1]);
        record.min = fieldSetFlags()[2] ? this.min : (java.lang.Long) defaultValue(fields()[2]);
        record.max = fieldSetFlags()[3] ? this.max : (java.lang.Long) defaultValue(fields()[3]);
        record.sumSquared = fieldSetFlags()[4] ? this.sumSquared : (java.lang.Long) defaultValue(fields()[4]);
        record.mean = fieldSetFlags()[5] ? this.mean : (java.lang.Double) defaultValue(fields()[5]);
        record.variance = fieldSetFlags()[6] ? this.variance : (java.lang.Double) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
