/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.Sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BodyStyle { 
  CHASSIS, CONVERTIBLE, COUPE, HATCHBACK, MINIVAN, PICKUP, SUV, SEDAN, VAN, WAGON  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BodyStyle\",\"namespace\":\"com.refactorlabs.cs378.Sessions\",\"symbols\":[\"CHASSIS\",\"CONVERTIBLE\",\"COUPE\",\"HATCHBACK\",\"MINIVAN\",\"PICKUP\",\"SUV\",\"SEDAN\",\"VAN\",\"WAGON\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
