/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.Sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventType { 
  CHANGE, CLICK, DISPLAY, EDIT, SHOW, SUBMIT, VISIT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"com.refactorlabs.cs378.Sessions\",\"symbols\":[\"CHANGE\",\"CLICK\",\"DISPLAY\",\"EDIT\",\"SHOW\",\"SUBMIT\",\"VISIT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
