/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.Sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum VehicleCondition { 
  New, Used  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"VehicleCondition\",\"namespace\":\"com.refactorlabs.cs378.Sessions\",\"symbols\":[\"New\",\"Used\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
